# Generated by Django 4.0.4 on 2022-06-14 23:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
