# Generated by Django 4.0.4 on 2022-07-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0002_room_room_id_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='participant',
            field=models.ManyToManyField(blank=True, to='raffle.participant'),
        ),
    ]
