# Generated by Django 4.0.4 on 2022-08-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0004_room_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
