# Generated by Django 4.0.4 on 2022-08-16 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0005_alter_participant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='raffle.participant')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raffle.room')),
                ('selected_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_participant', to='raffle.participant')),
            ],
        ),
    ]
