# Generated by Django 4.0.4 on 2022-08-16 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raffle', '0006_raffleparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participant_adm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant_adm', to='raffle.participant'),
        ),
    ]
